export const SIGNINMODAL = 'SIGNIN-MODAL';
export const SIGNUPMODAL = 'SIGNUP-MODAL';
export const OTPMODAL = 'OTP-MODAL';
export const USERTYPEMODAL = 'USERTYPE-MODAL';
export const SCHEDULEVISITMODAL = 'SCHEDULEVISITMODAL';
export const REFERRALMODAL = "REFERRALMODAL";
export const BOOKINGMODAL = "BOOKINGMODAL";
export const BANNERIMAGE = "BANNERIMAGE";
export const TERMSCONDITIONMODAL="TERMSCONDITIONMODAL"

