export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_OAUTH_DATA = 'FETCH_USER_OAUTH_DATA';
export const FETCH_OTP_VERIFICATION_DETAIL='FETCH_OTP_VERIFICATION_DETAIL';
export const OTP_VERIFIED='OTP_VERIFIED';
export const OTP_VERIFIED_FOR_LINKING='OTP_VERIFIED_FOR_LINKING';